@startwbs system_hierarchy
scale 1920*1080
!theme spacelab

* DART Vehicle

** Ascent System
*** Fins
*** Ascent Motor
*** Motor Tube
*** Centering Rings
*** Rail Buttons

** Abort System
*** Parachute
*** Shock Cords
*** Pyrotechnic Charge
*** Connection Hardware

** Landing System
***:Thrust Vector Control
(TVC) Mechanism;
*** Descent Motor
*** Landing Legs
***:Landing Leg Deployment
Mechanism (LLDM);

** Avionics System
*** Flight Software
*** Flight Computer
**** XBee Radio Module
**** Barometer
**** IMU
**** Microcontroller

** Payload Systen
*** Payload Bay
*** Payload
@endwbs