name: generate_dnts

on:
    schedule:
        - cron: "30 22 * * *"
jobs:
    setup:
        runs-on: windows-latest
        steps:
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run:  |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
    iterate_datetime_possibilities:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                ls
                cd .\simulation\6DOF\Python\
                ls
                .\generate_dnts.bat