name: launch_information

on:
    schedule:
      - cron: 30 5 * * *
jobs:
    iterate_datetime_possibilities:
        runs-on: windows-latest
        steps:
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run automation script
              timeout-minutes: 60
              run: |
                cd .\simulation\6DOF\Python\DNT\
                .\generate_dnts.bat